name: 'action-remote-sync'
description: 'This action is automatically synchronizing the trigger branch of a repository it is implemented into with a given remote server. This server needs to offer access to a synchronization API (see [here](https://github.com/kaskadi/remote-sync-api)).'

env:
  REMOTE_IP:
    description: 'IP of the server where the synchronization API is running.'
    required: true
  AUTH_TOKEN:
    description: 'Authorization token used by the API to authorize requests.'
    required: true

runs:
  using: 'node12'
  pre: 'src/pre.js'
  main: 'src/main.js'
  post: 'src/post.js'
