name: 'action-remote-sync'
description: 'This action is automatically synchronizing the trigger branch of a repository it is implemented into with a given remote server. This server needs to offer access to a synchronization API (see [here](https://github.com/kaskadi/remote-sync-api)).'

env:
  SYNC_API_ROOT:
    description: 'Root of the server where the synchronization API is running. This should follow the following format: `http(s)://{DOMAIN}/{API_ROOT}`.'
    required: true
  SYNC_API_AUTH_TOKEN:
    description: 'Authorization token used by the API to authorize requests.'
    required: true

runs:
  using: 'node12'
  pre: 'src/pre.js'
  main: 'src/main.js'
